Build_2025.02.04.22.44_TS2314エラーに対する修正
[変更内容]
 - TS2314エラーに対する修正
   - src/Character.ts(76,18): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
   - Map は Map<K, V> という形で、キー (K) と値 (V) の型を指定する必要がある
 - 修正
   - Mapクラスをインポート