Build_2025.02.04.23.07_TS2339エラーに対する修正
[変更内容]
 - TS2339エラーに対する修正
   - src/mole.ts(17,10): error TS2339: Property 'width' does not exist on type 'Mole'. など
   - CharacterクラスのプロパティがMoleクラスに正しく継承されていない
 - 修正内容
   - Characterクラスのimport設定を修正
   - src/mole.ts(2,27): error TS2307: Cannot find module './character' or its corresponding type declarations.