Build_2025.02.05.07.20_TS5096エラーに対する修正
[変更内容]
 - TS5096エラーに対する修正
   - tsconfig.app.json(13,35): error TS5096: Option 'allowImportingTsExtensions' can only be used when either 'noEmit' or 'emitDeclarationOnly' is set.
     tsconfig.node.json(12,35): error TS5096: Option 'allowImportingTsExtensions' can only be used when either 'noEmit' or 'emitDeclarationOnly' is set.
 - 修正内容
   - 'allowImportingTsExtensions'を削除