Build_2025.02.04.21.00_TS6133エラーに対する修正
[変更内容]
 - TS6133エラーに対する修正 #75
   - error TS6133: 'XXX' is declared but its value is never read.